### ISSUE TITLE
An exception occured

### ISSUE THREAD

**Issue by kuwoh** [ctrninja/osu-3DS#2]
o2DS
11.6.0, B9S + Luma
exception type: data_abort

here's the dump file:
[crash_dump_00000024 = osu-3ds.zip](https://github.com/ctrninja/osu-3DS/files/1564845/crash_dump_00000024.osu-3ds.zip)

**Comment by ctrninja** [comment]
Hmm, I'll take a look at this. Thanks!

**Comment by ctrninja** [comment]
Wait did you download the default osu! skin and put it in romfs???

**Comment by kuwoh** [comment]
where is romfs? is it the folder containing the 3dsx file?

**Comment by ctrninja** [comment]
You need to put it in the romfs in the source code, make a folder in the source code called romfs and then inside the romfs folder make a folder called default and put your skin assets in it.

**Comment by kuwoh** [comment]
ah alright, thank you
